### ISSUE TITLE
[XMAN] Perte de connexion

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#10]
### Environment

- Demo
- Operational

### Perte de données XML ou perte de connexion avec MUAC
Les secteurs doivent être au courant de la perte de connexion mais le CDS doit avoir une notification "forte" qu'il devrait acquitter sur son dashboard ou a defaut sur sa page XMAN dédiée

### Notification sur CWP et SPVR de même nature
Les notifications sont sur le bandeau superieur ? ou est elle aussi sur le bandeau lateral (genre changement de couleur clignotement?)

**Comment by kouak** [comment]
Tasks :
- [x] Make orchestrator aware of its dependencies statuses (https://github.com/devteamreims/4me.xman.orchestrator/commit/a5043b2e732bcbd07b326b60417e573b2287be83)
- [ ] Display status in HMI

**Comment by kouak** [comment]
Xman page : http://i.imgur.com/z0CTBav.png
Status page : http://i.imgur.com/N5fsDSi.png

https://github.com/devteamreims/4me.react/commit/1582828001f7abea99f3556c22d789cafe15e266
