### ISSUE TITLE
Correct "Elastic" mechanism behaviour for FMP client

### ISSUE THREAD

**Issue by OneATC** [devteamreims/4ME#103]
### Environment
- Operational

### Actual behaviour
At the FMP position, the elastic mechanism revert back to XMAN.

### Expected behaviour
At the FMP position, the elastic mechanism should revert back to the current OPS Room Config.

**Comment by kouak** [comment]
Currently, the "elastic" mechanism should only take place on a normal CWP with open sectors bound to it.

If this happens, then it's a bug.

Can you provide some kind of confirmation this is actually happening by trying it out in the control room on the FMP client ?

**Comment by OneATC** [comment]
I confirm the following behaviour just checked in ops :

   - FMP: Elastic is ON and reverting to ARCID (On FMP request would be
   better if reverting to Room Conf).
   - CDS :  Elastic is ON and reverting to Room Conf (OK)
   - CWP bound to a sector :  Elastic is ON and reverting to XMAN (OK)
   - CWP not bound to sector : Elastic is ON and reverting to XMAN (for me
   it's OK as well)


2016-07-26 11:33 GMT+02:00 Benjamin Beret <notifications@github.com>:

**Comment by kouak** [comment]
Thanks for confirming.

Found the bug. Deployed this stuff without really coding all the functionalities :)

This will be fixed shortly.

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.react/commit/6d84d5787c9fd3bdb009f4fe3d5ffbf1b1d42f3e
