### ISSUE TITLE
Correct "Elastic" mechanism behaviour for CWP client

### ISSUE THREAD

**Issue by OneATC** [devteamreims/4ME#104]
### Environment
- Operational

### Actual behaviour
On CWP, whatever the delay situation and the sector, the elastic mechanism reverts back to XMAN. Sometime it leads to revert toward and empty list (if there's no aircraft at all or no aircraft in the geofilter envelope).

### Expected behaviour
Only reverts back if there's a non-empty geofiltered list.

### Alternative behaviour
Only reverts back if there's a speed reduction to be applied (i.e. the notification indicator is not null)

**Comment by kouak** [comment]
This one is tricky.

The client only knows about the **selected** XMAN list. If the user clicks on "all flights" then the client has no way to know about the geo-filtered list.

What could be done quickly : only revert to XMAN page if the XMAN notification count is non-null.
When the XMAN list is updated and if there's an action required *in the selected filter*, then the elastic countdown could be triggered.
Also, the countdown should be stopped if the XMAN notification count reverts back to 0.

I fear this behaviour will be quite difficult to explain to users but should prove quite comfortable to use.

**Comment by OneATC** [comment]
Let's do it and we'll simplify the explanation by saying that the elastic
is triggered when there's a xman action expected in the filter selected by
the user.

2016-07-26 11:43 GMT+02:00 Benjamin Beret <notifications@github.com>:

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.react/commit/6d84d5787c9fd3bdb009f4fe3d5ffbf1b1d42f3e
