### ISSUE TITLE
Conf Naming

### ISSUE THREAD

**Issue by OneATC** [devteamreims/4ME#105]
### Environment
- Demo
- Operational

### Actual behaviour
FIR + URME is appearing as "KDFE"

### Expected behaviour
FIR + URME should be renamed "RFUE"

**Comment by kouak** [comment]
Just to make it clear so there's only one fix in there :

RFUE is 4E + 4H + KD + 2F + FIR
URME is 4E + 4H + KD + 2F

And that's it ?

**Comment by OneATC** [comment]
Yep ... that's correct !

2016-08-22 12:41 GMT+02:00 Benjamin Beret <notifications@github.com>:

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.core.mapping/commit/3d7c94a8850ae29a1ffa347b996cf871a625f1dd

Bumped core.mapping version 0.1.2
https://github.com/devteamreims/4me.core.mapping/releases/tag/0.1.2
