### ISSUE TITLE
[XMAN] Live Data Demo

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#12]
### Environment

- Demo

### Basculement possible
Tu peux basculer sur les données live dès aujourd'hui si tu veux
Peut être tu as rencontré des problèmes de connexion avec MUAC ces deux derniers jours, MUAC est passé ce matin sur le backup et étudie le problème en interne.

Pour la démo à Zurich on fera avec les données live même si il n'y a pas de Zurich dedans ca claquera déjà bien comme ca ;)

Merci

**Comment by kouak** [comment]
C'est fait.

**Comment by kouak** [comment]
Post d'annonce sur le site : 
https://github.com/devteamreims/devteamreims.github.io/blob/master/_posts/2016-04-23-xman-live-data.markdown
http://devteamreims.github.io/2016/04/23/xman-live-data.html
