### ISSUE TITLE
[Mapping] Text Total Opened sectors

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#13]
### Environment

- Demo
- Operational

 Modifer le texte pour le rendre plus lisible plus gros et changer la couleur

**Comment by kouak** [comment]
Fixed here : https://github.com/devteamreims/4me.react/commit/1df880aa2de36d9681052c15dfb2aa3b279f1365

Result :
http://i.imgur.com/qHLHOIk.png
