### ISSUE TITLE
[Mapping] regroupement de nuit et ouverture du matin

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#14]
### Environment

- Demo
- Operational

### Time and date (UTC)

Sur un regroupement 5EH, 4ME ne propose au superviseur que 3 choix "5EH" (bug) au lieu de KDFE.

Si URMN est en 31, un clic en 32 propose URMN, 5R et 4N. Un ajout de HNR, KHNR, UXNR et UKNR peut aider pour les ouvertures "en chapeau" qui prennent pas mal de clics sinon.

**Comment by kouak** [comment]
Résolu : https://github.com/devteamreims/4me.core.mapping/commit/aeeaf7f438680f48fed76dd0cfa7fb232783e2bc
https://github.com/devteamreims/4me.core.mapping/commit/767237c8837cbfe53945b9e664733f4550ad0419
