### ISSUE TITLE
Interest Volume/Surface

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#15]
### Environment

- Demo
- Operational

For XMAN Flows the interest volume cannot be aligned with sector boundary. 
For EGLL we have to extended the surface of interest for the sectors N,R,F,D and define a special one for E (for EDDS departures)
We can either create new volumes or surface of interest or extended flow by flow.

**Comment by kouak** [comment]
Geo config is here : https://github.com/devteamreims/4me.xman.orchestrator/tree/master/config/sectors

**Comment by kouak** [comment]
Imported KML stuff: https://github.com/devteamreims/4me.xman.orchestrator/commit/39ffb58940c933d8e8e3577b447393a9fb76686f

Filtering in sectors should consider new surfaces. Closing.
