### ISSUE TITLE
Demos fail at downloading css et js bundles with err net::ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by anonymousatc** [devteamreims/4ME#16]
I did a bit of research. Is there a proxy running at http://4me.home.kouak.org/ ?
If so, it could have something to do with the proxy caching assets...

### Environment

- Demo

### Current setup
Chrome 50.0.2661.86 (64-bit)
Ubuntu 15.10

**Comment by kouak** [comment]
Hit full disk on the server.

Should be doing fine now !
