### ISSUE TITLE
XMAN Sleeping time

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#17]
### Environment

- Demo
- Operational
No XMAN Advisory can be display on the HMI out of the followed scheduled time :
From 06h30 to 22h00 UTC (Winter time)
From 05h30 to 21h00 UTC (Summer Time)

When the TTO COP is inside the night time 4Me should filter the delay information (not relevant before the opening of the second runway at LHR) and the mach advisory

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.xman.orchestrator/commit/02dc739fda95e197b49140fee858139f27c92e49

Done here.

Is this something we'll see happening with all destinations or will remain specific to EGLL ?

**Comment by OneATC** [comment]
These times are EGLL specific but the principle may happen to other airports.

**Comment by kouak** [comment]
TODO : Cleanup code and implement this in `shouldAdvisoryUpdate`

**Comment by kouak** [comment]
Closing for now, didn't come up with a good solution, will reevaluate when LSZH comes into play.

**Comment by kouak** [comment]
Reopened : provided time intervals are wrong.

Correct ones are :
* Winter : 0630Z to 2100Z
* Summer : 0530Z to 2000Z

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.xman.orchestrator/commit/902cf94d4fd3504b34155f48cf8e55a309354dfb
