### ISSUE TITLE
[XMAN] Captured/frozen flight status

### ISSUE THREAD

**Issue by kouak** [devteamreims/4ME#18]
### Environment

- Demo
- Operational

### Expected behaviour

XMAN flight list should not display speed advisories unless the flight is in a certain area. We should not filter out these flights. We need to have them in the flight list but without a published mach reduction advisory.

Likewise, flights in a certain area should be "frozen", meaning a new advisory won't be issued no matter what.

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.xman.orchestrator/commit/4e2592b9347aaeffbe62308a5bc374430be7b3da

Solution is to define a "capture" area and use geo information.

**Comment by Rubbens** [comment]
OK will provide 
EGLL capture area = 4N+5R+KD2F+Buffer area
LSZH capture area = 4E+4H

**Comment by kouak** [comment]
Updated initial issue with frozen status. For consistency sake, we should implement the same logic for the "frozen" status, i.e define a geographical area in which flights won't be issued a different advisory.

**Comment by kouak** [comment]
Geo implementation : https://github.com/devteamreims/4me.xman.orchestrator/blob/ecc35ae52ad3360880d3f7b0d0c72186a82fdce4/src/geo/index.js#L78-L100

**Comment by Rubbens** [comment]
Attached in my mail : KML for LHR : Sector interest area + frozen horizon + display horizon + active horizon

**Comment by kouak** [comment]
Imported KML stuff : https://github.com/devteamreims/4me.xman.orchestrator/commit/39ffb58940c933d8e8e3577b447393a9fb76686f

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.xman.orchestrator/commit/4ab2a2db3c911b3eb6e821d2be70a0ce2f93004f

Done here, needs testing.

Will update when deployed on the demo.

**Comment by kouak** [comment]
Deployed on demo.

Closing pending review.
