### ISSUE TITLE
Advisory Alarm Status

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#19]
### Environment

- Demo
- Operational

The delay and the associated mach advisory reduction can pop up everywhere inside the XMAN horizon, until a limit (XMAN frozen horizon) where no XMAN advisory can pop up.

Between the 2 horizon, considering the advisory has pop up at T, after T+X min (figures can be modified, let's have X=4 for the beginning) an alarm should be raised to inform the controller he is out out the best time frame to reduce the aircraft.
No flashing alarm can be accepted in OPS Room, a slight color changes or a border change should be enough.

**Comment by kouak** [comment]
Won't fix. Idea dropped.
