### ISSUE TITLE
[MAPPING] Make suggestion buttons more visible

### ISSUE THREAD

**Issue by kouak** [devteamreims/4ME#21]
### Environment

- Demo
- Operational

### Actual behaviour
Users reported a lack of visibility for the suggestion buttons. Screenshot for reference: http://i.imgur.com/MN4quGJ.png

### Possible solutions
Use accent color instead of primary color.
Make the buttons bigger.
Hide manual sector selectors to have the buttons stand out more.

**Comment by kouak** [comment]
Usage of accent color : http://i.imgur.com/xVZsgSK.png
Usage of accent color + larger font size : http://i.imgur.com/RvqcPnn.png

**Comment by OneATC** [comment]
Option 2 accent color + lager font size

G²

2016-05-02 17:52 GMT+02:00 Benjamin Beret <notifications@github.com>:

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.react/commit/719857f5693a3a8f3026f8e1049e429256087aa9
