### ISSUE TITLE
Margins XMAN list 

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#23]
### Environment

- Demo
- Operational

The space between two lines is too big and limits the number of XMAN ARCID on one page.

Can't we reduce the marging and maybe if needed the two lines fiels to make only one line (as the 24" is large enough to diplay all the data)

**Comment by kouak** [comment]
Related to #6

**Comment by kouak** [comment]
http://i.imgur.com/3lQ0QrX.png
http://i.imgur.com/itjIAuq.png
https://github.com/devteamreims/4me.react/commit/4ef9a31d9cb70fcb370f63692f6fa4ddd6a5bdee
