### ISSUE TITLE
Colors and material design 

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#24]
### Environment

- Demo
- Operational

### Undo Button :
Currently the undo turns red when XMAN action has been clicked, red is not welcome on OPS HMI. Can't we modify to a dimmed color?

### Yellow advisory 
When a XMAN action has been send to the crew and when this reduction is different from the Mach Advisory the Yellow color remain strong.
Can't we reduce the intensuty of the yellow to still notify to the ATC the speed is different from the advisory but without disturbing too much.

### White button
White is too white. Would it be possible to dim the white in the action button area?

**Comment by kouak** [comment]
Undo button : white + black text
Dimmed color : grey700
Yellow advisory : orange200

**Comment by kouak** [comment]
Done : http://i.imgur.com/3dzHrJo.png

https://github.com/devteamreims/4me.react/commit/0718311bf117c498b78c8d989595fb4d4a326c3b
https://github.com/devteamreims/4me.react/commit/b41743b692d09537b7270d9bd2cd7e053cb9f7d0
