### ISSUE TITLE
Filtering Enhancement

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#27]
### Default mode
Highlight pending action needs to be always active, the dedicated button should be removed
The default filter set up should be 
- vertical filter NO
- geogrphical filter YES

### Filter options
Two options filter button should be proposed
#### Vertical filter
The aim is to see only the XMAN traffic in the vertical limit of the sector interest volume
#### Global visualisation
Display all the XMAN traffic in the display area

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.react/commit/a5df849ad868553d4f45748a60d3f0521d7b5f6e
