### ISSUE TITLE
Delay Color code 

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#30]
##### Material Design

- Demo
- Operational

To be consistent with the XMAN action I propose to change the color coding of the delay
- Orange 800 when total delay equal and up to 7min
- Yellow 300 (can be modified to stay consistent with already used material design) when total delay is between 5 and 7mn
- Green (the one use in the advisory button) when delay is less than 5mn

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.react/commit/57f520485539d3d40dae98740ff20723083d7873

http://i.imgur.com/EKHwTQp.png
http://i.imgur.com/Iwia0lm.png
http://i.imgur.com/55p2esS.png
