### ISSUE TITLE
Demo Kickoff

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#32]
Will the new features will be on the demo tomorrow or will we use the previous version?

**Comment by kouak** [comment]
Deployed just now.

Should be visible after a force refresh (ctrl shift R / cmd shift R).

**Comment by Rubbens** [comment]
That's rocks

**Comment by kouak** [comment]
http://4me.dsna.fr/2016/05/08/getting-ready-for-prime-time.html
