### ISSUE TITLE
Tech Supervisor HMI

### ISSUE THREAD

**Issue by kouak** [devteamreims/4ME#35]
4ME must ship with a dedicated app for our tech supervisors.

Status of each component of the system should be displayed, and should help the tech supervisor identify wether an outage is local or remote.

**Comment by kouak** [comment]
Each component should provide a /status API endpoint with everything needed to build our maintenance UI.
Each component should report about its dependencies.
Each component directly connected to clients via websocket should report the full list of clients with IP addresses to help identify faulty clients.

Maintenance UI will periodically poll those API endpoints. WebSockets are not involved to keep it simpler.

### Status endpoints
- [ ] xman.egll.fetcher
- [ ] flight.positions
- [ ] xman.orchestrator
- [ ] core.mapping
- [ ] arcid.flightplanFetcher

### WebSocket clients
- [ ] core.mapping (we have two types of sockets here, core sockets and mapping display sockets)
- [ ] arcid.flightplanFetcher
- [ ] xman.orchestrator

**Comment by kouak** [comment]
core.mapping : https://github.com/devteamreims/4me.core.mapping/commit/a5299f244cb872651fc483106c003a074e813141
xman.orchestrator : https://github.com/devteamreims/4me.xman.orchestrator/commit/224175477668f1b996af8647a434b187911c2e2a

**Comment by kouak** [comment]
arcid : https://github.com/devteamreims/4me.b2b.flightPlanFetcher/commit/c8cc2216846f41e5d6597cd65cd45182316280fb

**Comment by kouak** [comment]
Fetcher : https://github.com/devteamreims/4me.xman.fetcher/commit/eaf3ef32d9779306828068f4fc81e421300c23a3

**Comment by kouak** [comment]
Tech HMI preview: http://i.imgur.com/08Dj2lH.png

https://github.com/devteamreims/4me.tech-spvr/commit/933d3d823c2b4f96b1e20ff4a28256df6dc8a940

**Comment by Rubbens** [comment]
That rocks

-- 
Thomas Leparlier

Le 14 mai 2016 à 20:05:06, Benjamin Beret (notifications@github.com) a
écrit:

**Comment by kouak** [comment]
http://4me.dsna.fr/demos/tech-spvr.html

Some services are not reachable from the internet (XMAN fetcher, flight positions), hence the 'unknown' status.

Other services haven't been updated on the demo yet (MAPPING / ARCID) and don't present their status for now.

**Comment by kouak** [comment]
First iteration has been shipped. Closing this one pending feedback from end users.
