### ISSUE TITLE
YR

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#42]
By clicking everywhere tonight I managed to open KYR and HR.
http://imgur.com/WSvur69

Is it relevant to let YR to be a nominal sector with special status?

I would propose to make HYR as a single nominal sector

**Comment by OneATC** [comment]
Sustained !

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.xman.orchestrator/commit/3dce50b3ba4261a0122d4c4358aa20aac441a88a
https://github.com/devteamreims/4me.react/commit/08d83700bb1a1b08fc05c6afb620a1e2b402f724
https://github.com/devteamreims/4me.core.mapping/commit/4fb1e032a19fbf4a327f69b65f801d3bd9a22281

YR and HR don't exist anymore, they are now combined into a single HYR elementary sector.
