### ISSUE TITLE
Service Status Notification

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#48]
###Current behaviour 
The notification of service status is the same for all the clients

###Expected Behaviour
Notifcattion should be adapted to the level of knowledge of the clients 
CWP : Only level 1 notification service OK True/False
SPVR OPS : 2 level of notification : service and subservice
SPVR TECH : Adapted notofication per client and per subservice

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.react/commit/125e6cde57cdee986729254ed612839c34e54ed9
