### ISSUE TITLE
XMan Time Out

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#49]
### Expected Behaviour
After X mn without data from the AMAN an Time-out alarm needs to be display.
The list with the advisory should stay and smoothly erase regarding existing the dispaly area (Capure)

**Comment by kouak** [comment]
http://i.imgur.com/M4dqvvQ.png
https://github.com/devteamreims/4me.react/commit/3e7eda8fc6f910f8c3e74eee0232affd1bfc2de1
https://github.com/devteamreims/4me.xman.orchestrator/commit/cc674cd7cae57bb1663035317c335f2b5f35c30f

MAX_DATA_AGE is set to 120 seconds.

**Comment by Rubbens** [comment]
Regarding the Sherpa XMAN experience 5mn between 2 xml might happen
Currently Sherpa is set at 1200 sec because of the new connection process

Let's try to set at 600 sec to avoid bugs during OPS kickoff and reduce
this buffer later on

-- 
Thomas Leparlier

Le 16 mai 2016 à 11:26:52, Benjamin Beret (notifications@github.com) a
écrit:

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.xman.orchestrator/commit/254f246ce0937e3c8b7715ca007c74759beaa114
