### ISSUE TITLE
[MAPPING] Emergency radio information

### ISSUE THREAD

**Issue by kouak** [devteamreims/4ME#5]
Print backupped frequencies in the sector list after clicking on a CWP.

Print any non-backupped frequency in the dashboard as a warning for the supervisor.

Todo :
- [x] Have the frontend pull information from the backend (https://github.com/devteamreims/4me.core.mapping/commit/41c7019265c14c8cea37d17dba0ea247c977356a / https://github.com/devteamreims/4me.react/commit/1df880aa2de36d9681052c15dfb2aa3b279f1365)
- [x] Display information on the mapping dashboard (https://github.com/devteamreims/4me.react/commit/1df880aa2de36d9681052c15dfb2aa3b279f1365). For now, the popup appears after clicking the icon. It could be better to display/hide on mouse over. Consider this fixed for now, will update after feedback from users.
- [x] Implement backuped frequencies in cwp definitions (https://github.com/devteamreims/4me.core.mapping/commit/fb37ba78d6b822fe8d27035d1d2e325fc3e1c511)
- [x] Display information in the dialog after clicking on a CWP
- [x] Display icon under each CWP without backup on the dashboard

**Comment by kouak** [comment]
First step of implementation done.

Room status is properly displayed :
http://i.imgur.com/VnA9bnO.png
http://i.imgur.com/qHLHOIk.png

Todo :
- [ ] Implement backuped frequencies in cwp definitions (https://github.com/devteamreims/4me.core.mapping/tree/master/config/cwps)
- [ ] Display information in the dialog after clicking on a CWP

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.core.mapping/commit/fb37ba78d6b822fe8d27035d1d2e325fc3e1c511
https://github.com/devteamreims/4me.react/commit/9d75edff15d29ad862b2f5caf37a6f4e2d97f0a5
https://github.com/devteamreims/4me.react/commit/c209a04fcc6396a2b85eef1412af46a826bf04ba

**Comment by Rubbens** [comment]
In case of using a non nominal frequency in a sector such as a suppletive false alarm will pop up in RGR and Mapping CDS.

The frequency table is currently static, a dynamic table should avoid this false alarm

**Comment by kouak** [comment]
Closing this one for now. Basic functionnality is there, enhancements will fall into a different issue.
