### ISSUE TITLE
Dashboard 

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#50]
### Current behaviour
Clicking on the sector brings back to the dashboard.
All clients are set up to have the same dashboard XMAN

### Expected behaviour
Change the dashboard regarding the type of client : 
CDS - Mapping
FMP - ARCID
CWP - XMAN

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.react/commit/b1a09b5302ea6249b2c9f48521eca87d6efc3c66

**Comment by kouak** [comment]
react-router doesn't support replacing routes on runtime, commited fix was useless.

**Comment by kouak** [comment]
Workaround : https://github.com/devteamreims/4me.react/commit/930e0fd6676d2ed72ef7e452649cf73a2c1b4340

On app load (i.e after refreshing the page), xman will load no matter what. However, after loading everything we need from the backend, the topbar link will point to the proper destination.
