### ISSUE TITLE
SPVR Tech Demo

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#53]
### Environment : Demo
Broken link

**Comment by kouak** [comment]
Found a broken link here : http://4me.dsna.fr/demo/

This is now fixed.

Is it broken anywhere else ?

**Comment by Rubbens** [comment]
Apologise I was not clear enough.
Yes the broken link was this one and is fixed

Thxs

Le 16 mai 2016 à 14:54:22, Benjamin Beret (notifications@github.com) a écrit:

Found a broken link here : http://4me.dsna.fr/demo/

This is now fixed.

Is it broken anywhere else ?
