### ISSUE TITLE
ARCID Service

### ISSUE THREAD

**Issue by OneATC** [devteamreims/4ME#60]
### Environment
- Demo
- Operational

### ARCID Service should be renamed ETFMS 4D Profile

NB : That's for ATCO better understanding of the data provided.

**Comment by Rubbens** [comment]
ETFMS 4D Profile might be too long on the lateral bar I propose :
e4D
e4D P
ETFMS 4DP
e 4D Profile
Let's vote ;)

**Comment by sylvainmondou** [comment]
What about PLN, which should be self explanatory for the controllers?

**Comment by Rubbens** [comment]
ETFMS and Profile seems to be important for ATCO futur understanding

**Comment by kouak** [comment]
http://i.imgur.com/ELx8GTe.png

ETFMS PROFILE looks fine even with the UI zoomed.

**Comment by OneATC** [comment]
Perfect Thx Ben ...

2016-05-19 11:52 GMT+02:00 Benjamin Beret <notifications@github.com>:

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.react/commit/6b8d2f9e8f7bec52d8d79a75ba6fe22f332c4566
