### ISSUE TITLE
XMAN OFF button is not clear enough

### ISSUE THREAD

**Issue by kouak** [devteamreims/4ME#72]
Proposed solution :
- Button text : "XMAN ON/OFF"
- Toggle enabled in normal operation

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.react/commit/0b6e8bce3f48e19e7f0a66c172c28097103c056c

**Comment by Rubbens** [comment]
Can we have a screen shot of the new button to udapte the MUT

Thx ;)

**Comment by kouak** [comment]
http://i.imgur.com/YOqrzCZ.png
http://i.imgur.com/mMijYK9.png
