### ISSUE TITLE
OPS Room Configuration Orientation 

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#79]
OPS Room configuration copy is always presented the same way regarding less the position.

ATCO would appreciate to make in rotate by modulo 90° regarding the position in order to represent the real state of the OPS Room.

As an exemple on P21, ATCO would like to see P22 on the left instead of above as it is coded now

**Comment by kouak** [comment]
After discussion with @OneATC, we think this will bring more confusion than help to users.

Also, this will be a pain to code and will make our apps more dependant on LFEE environment.

**Comment by ClemGLAD** [comment]
Rotation will induce sectors written upside-down in the 4x aisle with 4-Flight deployement. Not very user-friendly
