### ISSUE TITLE
Missing trend

### ISSUE THREAD

**Issue by ClemGLAD** [devteamreims/4ME#82]
![img_20160613_162001 1](https://cloud.githubusercontent.com/assets/18627265/16015365/9bcfb166-3195-11e6-80b8-b8f4bf14a60d.jpg)
8000ft descent between BELDI and VEKIN but no trend displayed.

**Comment by kouak** [comment]
The displayed "trend" is the "exitTrend" from B2B responses.

We also display flight plan points only, and filter out ETFMS generated points. What happens here is that the descent starts between flight plan points, a "virtual" point is generated to mark this top of descent but it's not displayed.

We could reintegrate those virtual points in the list but the list will be longer and more difficult to read.

@OneATC, @Rubbens opinions ?

**Comment by OneATC** [comment]
Keep as it is ... we'll investigate for a vertical graph display soon
enough.
Le 14 juin 2016 12:17 PM, "Benjamin Beret" <notifications@github.com> a
écrit :

**Comment by kouak** [comment]
Roger.
