### ISSUE TITLE
FL and colors

### ISSUE THREAD

**Issue by ClemGLAD** [devteamreims/4ME#83]
Flight Levels are written different colours in the 4D ETFMS results. The logic (what colour for a level) is missing so ATCOs report these colours as useless for the time being.

**Comment by kouak** [comment]
The colors are far from useless. They greatly enhance readability of the list while scrolling.

There's no logic, colors are randomly attributed.

I fear removing colors will severely degrade user experience even though current behavior is hard to get for ATCOs.

**Comment by ClemGLAD** [comment]
Not to be misunderstood: I don't think colours are useless. I tried to report what I heard in the OPS room.

I suggest we use one colour for each significant sector layer e.g. Ground < Colour A < FL225 < Colour B < FL315 < Colour C < FL345 < Colour D < FL365 < Colour E < UNL

**Comment by Rubbens** [comment]
For the time we should keep color coding as it is for better segregation between each FL.

If there is a need to code via visualisation loyers we need to investigate deeper into details.

I propose you to close the issue until we have more feedback and reopen whenever it is needed

Let have a little bit more than 2 days of experience on the new service


Activé 14 juin 2016 à 20:28:13, ClemGLAD (notifications@github.com) a écrit:

Not to be misunderstood: I don't think colours are useless. I tried to report what I heard in the OPS room.

I suggest we use one colour for each significant sector layer e.g. Ground < Colour A < FL225 < Colour B < FL315 < Colour C < FL345 < Colour D < FL365 < Colour E < UNL
