### ISSUE TITLE
Paris sector US 4D ETFMS flights not all available for KD

### ISSUE THREAD

**Issue by ClemGLAD** [devteamreims/4ME#84]
When KD was openned, my planner was not able to find Profiles in US or TU sectors. I didn't catch the callsigns and I'll try to reproduce the event.

I just wanted to know if there is sector filter or if the buffer of entry in LFERMS is not too narrow for KD.

**Comment by kouak** [comment]
Traffic window is too narrow for now.
https://github.com/devteamreims/4me.b2b.flightPlanFetcher/blob/master/src/lib/b2b/query-builder.js#L14-L15

I used -2 min/+3 min. Maybe something like -10/+15 should be enough ?

**Comment by ClemGLAD** [comment]
Will the -10  sum with a 11 minute duration of LFERMS ? If not -20 might be useful (all KD length).

+3 is not be changed as far as I know.

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.b2b.flightPlanFetcher/commit/49b7ba4ee6d437b32e22546ad38ab5a7cc6df305
