### ISSUE TITLE
Virtual Keyboard Contrast

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#86]
### Operational
 In OPS Room virtual keyboard is hard to read.

Contrast settings and background could be solution to improve the keyboard use

**Comment by kouak** [comment]
Hard to read as "the text on the keys is hard to read" or "the keys are difficult to distinguish" ?

**Comment by OneATC** [comment]
Babasque reported that the white of the letters is to white ... I
personally think that it's the black that is too absolute ... should we try
the Adobe grey ?
Le 14 juin 2016 11:58 AM, "Benjamin Beret" <notifications@github.com> a
écrit :

**Comment by kouak** [comment]
http://i.imgur.com/dyAVW8z.png

For now, there are 3 colors :
- White for text
- Black for key background
- Dark grey for keyboard background

We need to keep sufficient contrast between the text and the key background (so the text is readable) and to keep sufficient contrast between key background and keyboard back ground (so the keys are visible).

What do you have in mind ?

**Comment by OneATC** [comment]
Something like that ... perhaps just with a little whiter letter?
Le 14 juin 2016 12:27 PM, "Benjamin Beret" <notifications@github.com> a
écrit :

**Comment by kouak** [comment]
Now :
![Now](http://i.imgur.com/TlY5jYW.png)

Proposal :
![Proposal](http://i.imgur.com/IGlHLEq.png)

Looks easier on the eye.

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.react/commit/edae01dd8cc2dae55a8e104b369725063d60986b

**Comment by Rubbens** [comment]
The proposed solution is ok and would definitely answer to the ops
requirement

Can we prepare a V0.1.2 with all this modifications you had to code after
the first week trial ?

Le 15 juin 2016 à 11:05:45, Benjamin Beret (notifications@github.com) a
écrit:

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.react/commits/0.2.1

Version 0.2.1 is ready, packaged and ready to deploy. Fabrice will be here tomorrow, we'll deploy it then.

**Comment by OneATC** [comment]
Great !
Le 15 juin 2016 11:05 AM, "Benjamin Beret" <notifications@github.com> a
écrit :
