### ISSUE TITLE
[Mapping] Ops Room Conf Change not distributed on the CWP HMI

### ISSUE THREAD

**Issue by OneATC** [devteamreims/4ME#9]
### Environment
- [x] Demo
- [ ] Operational

### Time and date (UTC)
16-04-19 05:40
### Expected behaviour
When changing the ops room configuration on the CDS HMI, the new conf should be automatically displayed on all other (CWP) HMI.
### Actual behaviour
There's a need to reload the page or restart the container.
### Additional information
However, the conf change is working for the XMAN service : when a CWP is "closed" the service is not clickable anymore.

**Comment by kouak** [comment]
Fixed here : https://github.com/devteamreims/4me.core.mapping/commit/4f46edd13a652e3b2e341e6efd0a2130146723e2
https://github.com/devteamreims/4me.react/commit/38170e9ea07a8340c10f9bcf30566b046dea62b6

Deployed to demo this morning.
