### ISSUE TITLE
Automatic Return to Dashboard

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#90]
### Operational

ETFMS Profile deployment rise the risk of remaining on the ETFMS Profile page and miss some XMAN actions.

When no mouse movement has been detected for the last Xsec, 4Me should revert to dashboard.

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.react/commit/84b1894f9725bf6b152478cc2feacceb1d81bcef
