### ISSUE TITLE
Consistency in sector naming with other supervisor tools

### ISSUE THREAD

**Issue by OneATC** [devteamreims/4ME#95]
### Environment
- Operational

### Actual behaviour
When HYR is band boxed with another layer the Y is still appearing. It's not consistent with the other tools.
Ex : We display KHYR

### Expected behaviour
HYR as ES should appear as HYR but when it's combined with something else the Y should disappear.
Ex : KHYR should be displayed as KHR

It's not so logic or even clever but that's how it works on the other tools.

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.core.mapping/commit/a81260ee1a01acc4d624d07ca23a8050a291a9db
