### ISSUE TITLE
Subscription not refreshed after sector change

### ISSUE THREAD

**Issue by Rubbens** [devteamreims/4ME#99]
### Environment
- Operational

### Actual behaviour
BAW8CF and BAW369 FL340 are shown on UF XMAN HMI

### Expected behaviour
Both aircraft are supposed to stay in KD

**Comment by kouak** [comment]
Edited the title.

Here's what happens :
Client is bound to KD+2F. XMAN client is subscribed to KD+2F.

Supervisor changes bound sectors to 2F only. Client does not inform the XMAN backend of its new subscription. Client still receives flights for KD.

This happens only when changing bound sectors on a client. If the transition is no sectors => sectors or sectors => no sectors, then the bug does not happen.

Current workaround is to change the selected filter (geo, geo + vertical, all) as this will properly reset the subscription to the backend.

Should be easy to patch.

**Comment by kouak** [comment]
https://github.com/devteamreims/4me.react/commit/ee604a30a5a6c21d417b3669c557e0aa36f8e2ad

Trying to deploy this fix before the holidays :).
